import { Member } from '../dataTypes/member';

export const MEMBERS: Member[] = [
    { id: 1, name: 'Changwon Yoo', title: 'S.M., Ph.D.', desc: 'Associate Professor, Biostatistics, FIU', type: 'Faculty', mailto: 'cyoo@fiu.edu'},
    { id: 2, name: 'Deodutta Roy', title: 'Ph.D.', desc: 'Professor, Environmental Health Science, FIU', type: 'Faculty', mailto: ''},
    { id: 3, name: 'Quentin Felty', title: 'Ph.D.', desc: 'Associate Professor, Environmental Health Science, FIU', type: 'Faculty', mailto: '' },
    { id: 4, name: 'Juan Liuzzi', title: 'Ph.D.', desc: 'Associate Professor, Dietetics & Nutrition, FIU', type: 'Faculty', mailto: '' },
    { id: 5, name: 'SungBae Park', title: 'M.D., Ph.D.', desc: 'Visiting Associate Professor, Biostatistics & Environmental Health Science, FIU', type: 'Faculty', mailto: '' },
    { id: 6, name: 'Jairo Ramos', title: '', desc: 'Ph.D.candidate, Environmental Health Science, FIU', type: 'Graduate Students', mailto: ''},
    { id: 7, name: 'Mark Preciados', title: '', desc: 'Ph.D candidate, Environmental Health Science, FIU', type: 'Graduate Students', mailto: '' },
    { id: 8, name: 'Efrain Gonzalez', title: '', desc: 'M.S. candidate, Statistics, FIU', type: 'Graduate Students', mailto: '' },
    { id: 9, name: 'Kaumudi Bhawe', title: '', desc: 'Ph.D candidate, Environmental Health Science, FIU', type: 'Graduate Students', mailto: '' },
    { id: 10, name: 'Zhenghua Gong', title: '', desc: 'M.S. candidate, Statistics, FIU', type: 'Graduate Students', mailto: '' },
    { id: 11, name: 'Juan Morales', title: '', desc: 'Ph.D candidate, Environmental Health Science, FIU', type: 'Graduate Students', mailto: '' },
    { id: 12, name: 'Stefanie Moore', title: '', desc: 'Staff Scientist, Biostatistics Center, Department of Biostatistics, FIU', type: 'Other', mailto: '' },
    { id: 13, name: 'Hamza Assaggaf', title: 'Ph.D', desc: '', type: 'Past Members', mailto: '' },
    { id: 14, name: 'Vincent Avecilla', title: 'Ph.D', desc: '', type: 'Past Members', mailto: '' },
    { id: 15, name: 'Lauren San Diego', title: '', desc: '', type: 'Past Members', mailto: '' },
    { id: 16, name: 'Luis Ramirez', title: 'MPH', desc: 'Gundersen Health System', type: 'Past Members', mailto: '' },
    { id: 17, name: 'Abhilash Cheeti', title: '', desc: '', type: 'Past Members', mailto: '' },
    { id: 18, name: 'Jose Gutierrez', title: 'MD, MPH', desc: 'Assistant Professor of Neurology at Columbia University Medical Center', type: 'Past Members', mailto: '' },
    { id: 19, name: 'Meredith L. Wilcox', title: 'MPH', desc: 'Ph.D. candidate, FIU', type: 'Past Members', mailto: '' },
    { id: 20, name: 'Brian Kunkle', title: 'MPH, Ph.D.', desc: 'Postdoctoral Fellow, University of Miami Hussman Institiute for Human Genomics', type: 'Past Members', mailto: '' },
    { id: 21, name: 'Erik Brilz', title: 'M.S.', desc: 'Axiom IT Solutions, Inc.', type: 'Past Members', mailto: '' },
];
